"use client";
import {useEffect,useRef,useState} from 'react';
import Image from 'next/image';
import Link from 'next/link';
import SkinAvatar from '../skin-avatar';
import type {Grade,Player,Audit} from '@/lib/admin-types';
import Statistics from './statistics';
import ServerHealth,{useServerHealth,HealthBadge} from './server-health';

export async function request<T>(path:string,body?:unknown,signal?:AbortSignal):Promise<T>{
 const response=await fetch('/api/admin/'+path,{method:body?'POST':'GET',body:body?JSON.stringify(body):undefined,headers:body?{'Content-Type':'application/json'}:{},cache:'no-store',signal});
 const data=await response.json();if(!response.ok)throw Error(response.status===401?'Ta session a expiré. Reconnecte-toi sur le site.':data.message||'La demande a échoué. Réessaie.');return data;
}
export const number=(value:number|string)=>new Intl.NumberFormat('fr-FR').format(typeof value==='string'?BigInt(value):value);
export const date=(value:string|null)=>value?new Date(value).toLocaleDateString('fr-FR',{day:'numeric',month:'short',year:'numeric',timeZone:'UTC'}):'Pas encore de connexion';
const activityDate=(value:string|null)=>value?new Intl.DateTimeFormat('fr-FR',{day:'numeric',month:'short',year:'numeric',hour:'2-digit',minute:'2-digit',timeZone:'UTC'}).format(new Date(value))+' UTC':'Pas encore de connexion';
export function Icon({name}:{name:string}){const paths:Record<string,string>={home:'M3 10 12 3l9 7v10h-6v-6H9v6H3z',players:'M16 21v-2a4 4 0 0 0-4-4H6a4 4 0 0 0-4 4v2M22 21v-2a4 4 0 0 0-3-3.87M9 11a4 4 0 1 0 0-8 4 4 0 0 0 0 8',stats:'M4 20V10M10 20V4M16 20v-7M22 20H2',grades:'m12 3 8 3v6c0 5-8 9-8 9s-8-4-8-9V6z',points:'M3 7c0-5 18-5 18 0s-18 5-18 0Zm0 0v5c0 5 18 5 18 0V7M3 12v5c0 5 18 5 18 0v-5',history:'M3 11a9 9 0 1 1 2 7M3 4v7h7M12 7v6l4 2',arrow:'M5 12h14m-5-5 5 5-5 5',search:'M21 21l-5-5M18 10a8 8 0 1 1-16 0 8 8 0 0 1 16 0',download:'M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6'};return <svg width="20" height="20" viewBox="0 0 24 24" fill="none" stroke="currentColor" strokeWidth="1.6" strokeLinecap="round" strokeLinejoin="round" aria-hidden="true"><path d={paths[name]||paths.home}/></svg>;}
const assets:Record<string,string>={aventurier:'poke-ball.webp',dresseur:'super-ball.png',ranger:'hyper-ball.png',champion:'honor-ball.png',legende:'luxe-ball.png',maitre:'maitre.webp'};
export function Badge({id,grades}:{id:string;grades:Grade[]}){const grade=grades.find(g=>g.id===id);return <span className="adm-grade"><Image src={'/grades/'+(assets[id]||assets.aventurier)} width={27} height={27} alt=""/><span style={{color:grade?.color||'#287851'}}>{grade?.label||id}</span></span>;}
type View='health'|'overview'|'players'|'grades'|'points'|'statistics'|'history';
const titles:Record<View,string>={health:'Santé du serveur',overview:'Vue d’ensemble',players:'Gestion des joueurs',grades:'Grades du serveur',points:'Points boutique',statistics:'Statistiques du serveur',history:'Historique des modifications'};
export default function AdminPanel({adminName}:{adminName:string}){
 const [view,setView]=useState<View>('statistics'),[grades,setGrades]=useState<Grade[]>([]),[refresh,setRefresh]=useState(0),[error,setError]=useState('');
 useEffect(()=>{const controller=new AbortController();request<{grades:Grade[]}>('grades',undefined,controller.signal).then(d=>setGrades(d.grades)).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[refresh]);
 const health=useServerHealth(refresh);
 const [filterGrade,setFilterGrade]=useState('');
 const navigate=(v:View)=>{setView(v);setError('');};
 return <div className="adm-shell"><aside className="adm-sidebar"><Link href="/admin" className="adm-brand"><Image src="/cobblemine-logo-approved.png" alt="Cobblemine" width={180} height={120} priority/><span>ADMINISTRATION</span></Link><nav aria-label="Administration">{(['overview','players','grades','points','statistics','health','history'] as View[]).map(v=><button key={v} className={v==='health'?'adm-health-nav':undefined} aria-current={view===v?'page':undefined} onClick={()=>navigate(v)}><Icon name={v==='overview'?'home':v==='statistics'||v==='health'?'stats':v}/>{v==='players'?'Joueurs':v==='grades'?'Grades':v==='statistics'?'Statistiques':v==='history'?'Historique':titles[v]}{v==='health'&&<HealthBadge status={health.status}/>}</button>)}</nav><div className="adm-sidebar-bottom"><Link href="/">Retour au site <Icon name="arrow"/></Link><Link href="/compte" className="adm-identity"><SkinAvatar username={adminName}/><span><strong>{adminName}</strong><small>Administrateur</small></span></Link></div></aside>
 <div className="adm-workspace"><header className="adm-top"><span>Administration <span className="adm-slash">/</span> <strong>{view==='players'?'Joueurs':titles[view]}</strong></span><Link href="/compte"><SkinAvatar username={adminName}/><span>{adminName}</span></Link></header><main className="adm-main"><div className="adm-heading"><div><p className="adm-eyebrow">COBBLEMINE · ESPACE ÉQUIPE</p><h1>{titles[view]}</h1><p>{view==='health'?'Performances, joueurs connectés et ressources du serveur. Actualisation toutes les 10 secondes.':view==='players'?'Comptes, grades et points boutique au même endroit.':view==='statistics'||view==='overview'?'Comprendre l’activité des joueurs et les performances de la boutique.':view==='grades'?'Les grades sont centralisés et synchronisés avec le serveur.':view==='history'?'Chaque intervention conserve son auteur, son motif et les valeurs modifiées.':'Les ajustements de points sont distincts des paiements de la boutique.'}</p></div><button className="adm-secondary" onClick={()=>setRefresh(r=>r+1)}><Icon name="history"/>Actualiser</button></div>
 {error&&<p className="adm-error" role="alert">{error}</p>}
 {(view==='statistics'||view==='overview')&&<Statistics key={view} refresh={refresh} grades={grades} overview={view==='overview'} onHealth={()=>navigate('health')}/>}
 {view==='health'&&<ServerHealth data={health.data} error={health.error}/>}
 {view==='players'&&<Players grades={grades} refresh={refresh} initialGrade={filterGrade}/>}
 {view==='grades'&&<div className="adm-grade-grid">{grades.map(g=><article className="adm-card" key={g.id}><Badge id={g.id} grades={grades}/><h2>{g.label}</h2><p>{g.id==='aventurier'?'Grade de base, sans expiration.':'Priorité '+g.priority+' · Attribution avec une date d’expiration.'}</p><button className="adm-secondary" onClick={()=>{setFilterGrade(g.id);navigate('players');}}>Voir les joueurs <Icon name="arrow"/></button></article>)}</div>}
 {view==='history'&&<History refresh={refresh}/>}
 {view==='points'&&<><div className="adm-note">Pour ajouter ou retirer des points, ouvre la fiche du joueur concerné. Un motif est obligatoire et chaque opération est conservée dans cet historique.</div><button className="adm-primary" onClick={()=>{setFilterGrade('');navigate('players');}}>Gérer les points d’un joueur <Icon name="arrow"/></button><History refresh={refresh} kind="points"/></>}
 </main><footer className="adm-footer">Cobblemine administration <span>Données réelles · Horaires et statistiques en UTC</span></footer></div></div>;
}
function Players({grades,refresh,initialGrade}:{grades:Grade[];refresh:number;initialGrade:string}){
 const [search,setSearch]=useState(''),[query,setQuery]=useState(''),[grade,setGrade]=useState(initialGrade),[status,setStatus]=useState(''),[page,setPage]=useState(1),[selected,setSelected]=useState<Player|null>(null),[data,setData]=useState<{players:Player[];total:number}|null>(null),[busy,setBusy]=useState(false),[mutating,setMutating]=useState(false),[error,setError]=useState(''),[revision,setRevision]=useState(0);
 useEffect(()=>{const timer=setTimeout(()=>{setQuery(search);setPage(1);},300);return()=>clearTimeout(timer);},[search]);
 // Loading state follows the start and completion of this external request.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');request<{players:Player[];total:number}>('players?'+new URLSearchParams({search:query,grade,status,page:String(page)}),undefined,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[query,grade,status,page,refresh,revision]);
 return <div className={'adm-players-layout'+(selected?' has-selection':'')}><section className="adm-player-list" aria-busy={busy}><div className="adm-toolbar"><label className="adm-search"><Icon name="search"/><input aria-label="Rechercher un joueur" placeholder="Rechercher un pseudo ou un email" value={search} onChange={e=>setSearch(e.target.value)}/></label><select aria-label="Filtrer par grade" value={grade} onChange={e=>{setGrade(e.target.value);setPage(1);}}><option value="">Tous les grades</option>{grades.map(g=><option value={g.id} key={g.id}>{g.label}</option>)}</select><select aria-label="Filtrer par statut" value={status} onChange={e=>{setStatus(e.target.value);setPage(1);}}><option value="">Tous les statuts</option><option value="online">En ligne</option><option value="active">Actifs</option><option value="banned">Suspendus</option></select></div>{error&&<p className="adm-error" role="alert">{error}</p>}<div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Joueur</th><th>Grade</th><th>Points</th><th>Dernière activité</th></tr></thead><tbody>{data?.players.map(p=><tr key={p.id} className={selected?.id===p.id?'selected':''}><td><button className="adm-player-link" disabled={mutating} onClick={()=>setSelected(p)} aria-label={'Gérer '+p.username}><SkinAvatar username={p.username}/><strong>{p.username}</strong></button></td><td><Badge id={p.grade} grades={grades}/></td><td>{number(p.points)}</td><td><span className={'adm-status '+(p.banned?'is-banned':p.online?'is-online':'')}>{p.banned?'Suspendu':p.online?'En ligne':activityDate(p.lastSeenAt)}</span>{(p.banned||p.online)&&p.lastSeenAt&&<div className="adm-muted"><time dateTime={p.lastSeenAt}>{activityDate(p.lastSeenAt)}</time></div>}</td></tr>)}</tbody></table>{!data&&busy?<div className="adm-empty">Chargement des joueurs…</div>:data?.players.length===0?<div className="adm-empty">Aucun joueur ne correspond à ces filtres.</div>:null}</div><Pagination page={page} total={data?.total||0} size={20} onChange={setPage} busy={busy}/></section>{selected&&<PlayerDetail key={selected.id} initial={selected} grades={grades} refresh={refresh} onClose={()=>{if(!mutating)setSelected(null);}} onBusy={setMutating} onChanged={()=>setRevision(r=>r+1)}/>}</div>;
}
function PlayerDetail({initial,grades,refresh,onClose,onBusy,onChanged}:{initial:Player;grades:Grade[];refresh:number;onClose:()=>void;onBusy:(value:boolean)=>void;onChanged:()=>void}){
 const [player,setPlayer]=useState(initial),[grade,setGrade]=useState(initial.grade),[expiry,setExpiry]=useState(initial.gradeExpiresAt?.slice(0,16)||''),[amount,setAmount]=useState(''),[direction,setDirection]=useState(1),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState(''),[confirmBan,setConfirmBan]=useState(false),[revision,setRevision]=useState(0);
 const retry=useRef<{key:string;signature:string}|null>(null);
 useEffect(()=>{const controller=new AbortController();request<{player:Player}>('players/'+initial.id,undefined,controller.signal).then(d=>{setPlayer(d.player);setGrade(d.player.grade);setExpiry(d.player.gradeExpiresAt?.slice(0,16)||'');}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[initial.id,refresh,revision]);
 async function save(change:unknown){
  if(busy)return;if(reason.trim().length<3){setError('Ajoute un motif de trois caractères minimum.');return;}
  const signature=JSON.stringify({change,reason:reason.trim()});if(retry.current?.signature!==signature)retry.current={key:crypto.randomUUID(),signature};
  setBusy(true);onBusy(true);setError('');setMessage('');try{await request('players/'+player.id+'/actions',{requestId:retry.current.key,reason:reason.trim(),change});retry.current=null;setRevision(r=>r+1);onChanged();setMessage('Modification enregistrée et historisée.');setReason('');setAmount('');setConfirmBan(false);}catch(e){setError(e instanceof Error?e.message:'Modification impossible.');}finally{setBusy(false);onBusy(false);}
 }
 return <aside className="adm-detail" aria-label={'Fiche de '+player.username}><button className="adm-close" onClick={onClose} disabled={busy} aria-label="Fermer la fiche">×</button><div className="adm-detail-identity"><SkinAvatar username={player.username}/><div><h2>{player.username}</h2><span className={'adm-status '+(player.banned?'is-banned':player.online?'is-online':'')}>{player.banned?'Compte suspendu':player.online?'En ligne':'Compte actif'}</span></div></div><dl className="adm-facts"><div><dt>Inscription</dt><dd>{date(player.createdAt)}</dd></div><div><dt>Dernière activité</dt><dd>{activityDate(player.lastSeenAt)}</dd></div><div><dt>Temps de jeu</dt><dd>{number(Math.floor(Number(player.playtimeSeconds)/3600))} h {Math.floor(Number(player.playtimeSeconds)/60)%60} min</dd></div><div><dt>Email</dt><dd>{player.email}</dd></div></dl>
 <label className="adm-reason">Motif de la modification <span>Obligatoire pour chaque action</span><textarea maxLength={300} minLength={3} rows={3} value={reason} disabled={busy} placeholder="Ex. : récompense d’un événement" onChange={e=>setReason(e.target.value)}/></label>
 <fieldset disabled={busy} className="adm-fieldset"><legend>Grade du joueur</legend><Badge id={player.grade} grades={grades}/><label>Grade<select aria-label="Grade" value={grade} onChange={e=>setGrade(e.target.value)}>{grades.map(g=><option key={g.id} value={g.id}>{g.label}</option>)}</select></label>{grade!=='aventurier'?<label>Expiration (UTC)<input type="datetime-local" value={expiry} onChange={e=>setExpiry(e.target.value)}/></label>:<p className="adm-muted">Grade de base · sans expiration</p>}<button className="adm-secondary" onClick={()=>{if(grade!=='aventurier'&&(!expiry||!Number.isFinite(Date.parse(expiry+'Z')))){setError('Choisis une date d’expiration.');return;}void save({kind:'grade',grade,expiresAt:grade==='aventurier'?null:new Date(expiry+'Z').toISOString()});}}>Enregistrer le grade</button></fieldset>
 <fieldset disabled={busy} className="adm-fieldset"><legend>Points boutique</legend><div className="adm-balance"><strong>{number(player.points)} <small>points</small></strong><div className="adm-segment"><button aria-pressed={direction===1} onClick={()=>setDirection(1)}>Ajouter</button><button aria-pressed={direction===-1} onClick={()=>setDirection(-1)}>Retirer</button></div></div><label>Montant<input type="number" min="1" max="1000000" step="1" placeholder="Ex. : 100" value={amount} onChange={e=>setAmount(e.target.value)}/></label><button className="adm-secondary" onClick={()=>{const value=Number(amount);if(!Number.isInteger(value)||value<1||value>1000000){setError('Le montant doit être compris entre 1 et 1 000 000 points.');return;}void save({kind:'points',amount:value*direction});}}>{direction===1?'Ajouter les points':'Retirer les points'}</button></fieldset>
{error&&<p className="adm-error" role="alert">{error}</p>}{message&&<p className="adm-success" role="status">{message}</p>}{busy&&<p role="status">Enregistrement…</p>}
 <div className="adm-account-danger">{confirmBan?<><p>{player.banned?'Réactiver ce compte ?':'Suspendre ce compte et fermer ses sessions ?'}</p><div className="adm-button-row"><button className="adm-danger" disabled={busy} onClick={()=>void save({kind:'ban',banned:!player.banned})}>Confirmer</button><button className="adm-secondary" disabled={busy} onClick={()=>setConfirmBan(false)}>Annuler</button></div></>:<button className="adm-danger" disabled={busy} onClick={()=>setConfirmBan(true)}>{player.banned?'Réactiver le compte':'Suspendre le compte'}</button>}</div><History compact targetId={player.id} refresh={revision+refresh}/></aside>;
}
export function Pagination({page,total,size,onChange,busy}:{page:number;total:number;size:number;onChange:(n:number)=>void;busy:boolean}){const pages=Math.max(1,Math.ceil(total/size));return <div className="adm-pagination"><span>{total?`${(page-1)*size+1}–${Math.min(page*size,total)} sur ${number(total)}`:'0 résultat'}</span><div><button aria-label="Page précédente" disabled={busy||page<=1} onClick={()=>onChange(page-1)}>←</button><span>{page} / {pages}</span><button aria-label="Page suivante" disabled={busy||page>=pages} onClick={()=>onChange(page+1)}>→</button></div></div>;}
function changeText(item:Audit){if(item.action==='points')return `${item.before.points} → ${item.after.points} points`;if(item.action==='ban')return item.after.banned?'Compte suspendu':'Compte réactivé';return `Grade : ${String(item.after.grade)}${item.after.expiresAt?' · jusqu’au '+date(String(item.after.expiresAt)):''}`;}
function History({refresh,targetId,kind,compact=false}:{refresh:number;targetId?:string;kind?:string;compact?:boolean}){
 const [page,setPage]=useState(1),[data,setData]=useState<{items:Audit[];total:number}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 // Loading state follows the start and completion of this external request.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');const q=new URLSearchParams({page:String(page)});if(targetId)q.set('targetId',targetId);if(kind)q.set('kind',kind);request<{items:Audit[];total:number}>('history?'+q,undefined,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[refresh,page,targetId,kind]);
 return <section className={'adm-history '+(compact?'compact':'adm-card')}><h2><Icon name="history"/>{compact?'Dernières actions':'Journal des interventions'}</h2>{error&&<p className="adm-error" role="alert">{error}</p>}{busy&&!data&&<p className="adm-muted">Chargement…</p>}{data?.items.length===0&&<div className="adm-empty">Aucune modification administrative enregistrée.</div>}<ol>{data?.items.map(item=><li key={item.id}><div><strong>{compact?'':item.target+' · '}{changeText(item)}</strong><p>{item.reason}</p><small>{item.actor} · {date(item.createdAt)} à {new Date(item.createdAt).toLocaleTimeString('fr-FR',{timeZone:'UTC',hour:'2-digit',minute:'2-digit'})}</small></div></li>)}</ol>{(data?.total||0)>30&&<Pagination page={page} total={data?.total||0} size={30} onChange={setPage} busy={busy}/>}</section>;
}
