"use client";
import {useEffect,useState} from 'react';
import type {Stats,Grade} from '@/lib/admin-types';
import {request,number,date,Icon,Badge} from './panel';
const today=()=>new Date().toISOString().slice(0,10);
const ago=(days:number)=>new Date(Date.now()-days*86400000).toISOString().slice(0,10);
const percent=(n:number,d:number)=>d?new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(n/d):'—';
const duration=(seconds:number|null)=>seconds===null?'—':`${Math.floor(seconds/3600)} h ${Math.floor(seconds/60)%60} min`;
type Tab='all'|'players'|'shop'|'acquisition'|'technical';
export default function Statistics({refresh,grades,overview,onHealth}:{refresh:number;grades:Grade[];overview:boolean;onHealth:()=>void}){
 const [range,setRange]=useState({from:ago(29),to:today()}),[period,setPeriod]=useState('30'),[compare,setCompare]=useState(false),[tab,setTab]=useState<Tab>('all'),[data,setData]=useState<Stats|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState('');
 // Loading state follows the start and completion of this external request.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{const controller=new AbortController();setBusy(true);setError('');request<Stats>('statistics?'+new URLSearchParams(range),undefined,controller.signal).then(setData).catch(e=>{if(!controller.signal.aborted)setError(e.message);}).finally(()=>{if(!controller.signal.aborted)setBusy(false);});return()=>controller.abort();},[range,refresh]);
 function exportCsv(){if(!data)return;const lines=[['Date UTC','Joueurs actifs','Premières connexions observées','Inscriptions'],...data.daily.map(d=>[d.day,d.active,d.newcomers,d.signups]),[],['Indicateur','Valeur'],['Période',data.from+' / '+data.to],['Début du suivi',data.summary.collectionStartedAt],['Joueurs actifs uniques',data.summary.active],['Inscriptions',data.summary.signups],...data.retention.map(r=>['Rétention J'+r.day,r.eligible?String(r.retained/r.eligible):'Non disponible']),['Achats','Non collectés'],['Revenus','Non collectés']];const csv='\uFEFF'+lines.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const link=document.createElement('a');link.href=url;link.download=`cobblemine-statistiques-${data.from}-${data.to}.csv`;link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 const visible=(which:Tab)=>tab==='all'||tab===which;
 const s=data?.summary,r7=data?.retention.find(r=>r.day===7);
 return <div aria-busy={busy}><div className="adm-stats-toolbar"><div className="adm-period"><label>Période<select value={period} onChange={e=>{setPeriod(e.target.value);if(e.target.value!=='custom')setRange({from:ago(Number(e.target.value)-1),to:today()});}}><option value="7">7 derniers jours</option><option value="30">30 derniers jours</option><option value="90">90 derniers jours</option><option value="custom">Personnalisée</option></select></label>{period==='custom'&&<><label>Du<input type="date" max={range.to} value={range.from} onChange={e=>{if(e.target.value)setRange(r=>({...r,from:e.target.value}));}}/></label><label>Au<input type="date" min={range.from} max={today()} value={range.to} onChange={e=>{if(e.target.value)setRange(r=>({...r,to:e.target.value}));}}/></label></>}</div><div className="adm-button-row"><label className="adm-compare"><input type="checkbox" checked={compare} onChange={e=>setCompare(e.target.checked)}/>Comparer</label><button className="adm-secondary" disabled={!data||busy||!!error} onClick={exportCsv}><Icon name="download"/>Exporter CSV</button></div></div>
 {!overview&&<nav className="adm-stat-tabs" aria-label="Catégories de statistiques">{([['all','Vue d’ensemble','stats'],['players','Joueurs & rétention','players'],['shop','Boutique & achats','points'],['acquisition','Acquisition','arrow'],['technical','Technique','history']] as [Tab,string,string][]).map(([id,label,icon])=><button key={id} aria-current={tab===id?'page':undefined} onClick={()=>setTab(id)}><Icon name={icon}/>{label}</button>)}</nav>}
 {error&&<p className="adm-error" role="alert">{error}</p>}{!data?<div className="adm-empty adm-card">{busy?'Chargement des statistiques…':'Les statistiques ne sont pas disponibles.'}</div>:<>
 <div className="adm-collection"><span className="adm-dot"/>Suivi des connexions depuis le {date(s!.collectionStartedAt)}. Les périodes antérieures ne sont pas reconstituées.{busy&&<span> Actualisation…</span>}</div>
 <div className="adm-kpis"><Metric icon="players" label="Joueurs actifs" value={number(s!.active)} note={compare?delta(s!.active,s!.previousActive):'Uniques sur la période'}/><Metric icon="players" label="Nouveaux inscrits" value={number(s!.signups)} note={compare?delta(s!.signups,s!.previousSignups):number(s!.registered)+' comptes au total'}/><Metric icon="history" label="Rétention J7" value={r7?percent(r7.retained,r7.eligible):'—'} note={r7?.eligible?`${r7.retained} revenus / ${r7.eligible} éligibles`:'Cohorte pas encore mature'}/><Metric icon="points" label="Chiffre d’affaires" value="—" note="Paiements non reliés" muted/><Metric icon="points" label="Achats" value="—" note="Non collectés" muted/><Metric icon="stats" label="Panier moyen" value="—" note="Non disponible" muted/></div>
 {visible('players')&&<div className="adm-chart-grid"><section className="adm-card"><div className="adm-card-heading"><h2><Icon name="players"/>Activité des joueurs</h2><div className="adm-legend"><span><i/>Actifs quotidiens</span><span><i className="green"/>Premières connexions</span></div></div><ActivityChart data={data.daily}/><p className="adm-caption">Connexions validées par le serveur · un joueur compte une fois par jour.</p></section><section className="adm-card"><h2><Icon name="history"/>Retours des joueurs</h2><div className="adm-retention-bars">{data.retention.map(r=><div key={r.day}><span>Jour {r.day}</span><div className="adm-progress"><span style={{width:(r.eligible?r.retained/r.eligible*100:0)+'%'}}/></div><strong>{percent(r.retained,r.eligible)}</strong><small>{r.eligible?`${r.retained} / ${r.eligible} joueurs`:'En attente'}</small></div>)}</div><p className="adm-caption">Présence exactement à J1, J7, J14 ou J30 après la première connexion observée. Seules les journées complètes et les cohortes éligibles sont comptées.</p></section></div>}
 {visible('shop')&&<div className="adm-chart-grid"><section className="adm-card"><h2><Icon name="points"/>Revenus et achats</h2><div className="adm-unavailable"><Icon name="points"/><h3>Relier les paiements de la boutique</h3><p>{data.commerce.reason}</p><div className="adm-unavailable-tags"><span>Revenus</span><span>Commandes</span><span>Remboursements</span><span>Produits populaires</span></div></div></section><section className="adm-card"><h2><Icon name="points"/>Mouvements de points boutique</h2><dl className="adm-values"><div><dt>Points ajoutés</dt><dd className="adm-positive">+{number(data.points.credited)}</dd></div><div><dt>Points retirés</dt><dd>−{number(data.points.debited)}</dd></div><div><dt>Opérations sur la période</dt><dd>{number(data.points.operations)}</dd></div></dl><p className="adm-caption">Ces opérations représentent les mouvements du portefeuille. Elles ne mesurent pas le chiffre d’affaires.</p></section></div>}
 {visible('players')&&<div className="adm-chart-grid"><section className="adm-card"><h2><Icon name="history"/>Rétention par cohorte</h2><p className="adm-caption">Regroupement par semaine de première connexion observée.</p><div className="adm-table-wrap"><table className="adm-table"><thead><tr><th>Semaine du</th><th>Joueurs</th><th>Éligibles J7</th><th>Rétention J7</th></tr></thead><tbody>{data.cohorts.map(c=><tr key={c.week}><td>{date(c.week)}</td><td>{c.players}</td><td>{c.eligible}</td><td className="adm-heat" style={{background:c.eligible?`rgba(83,168,115,${0.07+c.retained/c.eligible*0.3})`:undefined}}>{percent(c.retained,c.eligible)}</td></tr>)}</tbody></table>{!data.cohorts.length&&<div className="adm-empty">Les cohortes apparaîtront avec les prochaines connexions.</div>}</div></section><section className="adm-card"><h2><Icon name="grades"/>Répartition des grades</h2><div className="adm-grade-distribution">{data.grades.map(g=><div key={g.grade}><Badge id={g.grade} grades={grades}/><span>{number(g.players)} joueurs</span></div>)}</div><p className="adm-caption">État actuel des comptes actifs, toutes dates d’inscription confondues.</p></section></div>}
 {visible('acquisition')&&<section className="adm-card adm-funnel-card"><h2><Icon name="arrow"/>Parcours des nouveaux inscrits</h2><div className="adm-funnel">{[['Inscription',data.funnel.registered],['Ticket launcher',data.funnel.launcher],['Connexion serveur',data.funnel.game],['Premier achat',null]].map(([label,value])=><div key={String(label)}><span>{label}</span><strong>{value===null?'—':number(Number(value))}</strong><small>{value===null?'Paiements non reliés':percent(Number(value),data.funnel.registered)+' des inscrits'}</small></div>)}</div><p className="adm-caption">Comptes inscrits sur la période sélectionnée, ayant atteint chaque étape avant sa fin. « Ticket launcher » correspond à une demande d’accès au serveur.</p></section>}
 {visible('technical')&&<div className="adm-chart-grid"><section className="adm-card"><h2><Icon name="stats"/>Sessions & engagement</h2><dl className="adm-values"><div><dt>Joueurs en ligne maintenant</dt><dd><span className="adm-dot"/>{s!.online}</dd></div><div><dt>Sessions sur la période</dt><dd>{number(s!.visits)}</dd></div><div><dt>Durée moyenne observée</dt><dd>{duration(s!.averageSessionSeconds)}</dd></div><div><dt>Temps de jeu cumulé · toutes dates</dt><dd>{duration(Number(s!.totalPlaytimeSeconds))}</dd></div></dl><p className="adm-caption">La durée des sessions s’arrête au dernier signal reçu (environ toutes les 30 secondes). Le temps cumulé provient des statistiques Minecraft.</p></section><section className="adm-card"><h2><Icon name="history"/>Santé du serveur</h2><div className="adm-unavailable"><h3>Supervision en direct</h3><p>Consultez les TPS, les ressources et les joueurs dans la page dédiée.</p><button className="adm-secondary" onClick={onHealth}>Ouvrir la santé du serveur</button><div className="adm-unavailable-tags"><span>TPS</span><span>Mémoire</span><span>CPU</span><span>Joueurs</span></div></div></section></div>}
 </> }</div>;
}
function delta(now:number,before:number){if(!before)return now?'Pas de base de comparaison':'Aucune variation';const change=(now-before)/before;return `${change>=0?'+':''}${new Intl.NumberFormat('fr-FR',{style:'percent',maximumFractionDigits:1}).format(change)} sur la période précédente`;}
function Metric({icon,label,value,note,muted=false}:{icon:string;label:string;value:string;note:string;muted?:boolean}){return <article className={'adm-metric'+(muted?' is-muted':'')}><span className="adm-metric-icon"><Icon name={icon}/></span><div><strong>{value}</strong><h2>{label}</h2><p>{note}</p></div></article>;}
function ActivityChart({data}:{data:Stats['daily']}){
 const max=Math.ceil(Math.max(2,...data.map(d=>Math.max(d.active,d.newcomers)))/2)*2,x=(i:number)=>45+i/(Math.max(1,data.length-1))*565,y=(n:number)=>190-n/max*155;
 const path=(key:'active'|'newcomers')=>data.map((d,i)=>`${i?'L':'M'}${x(i)},${y(d[key])}`).join(' ');
 return <div className="adm-chart"><svg viewBox="0 0 650 230" role="img" aria-label="Joueurs actifs et premières connexions, par jour. Les données sont disponibles dans l’export CSV.">{[0,0.5,1].map(n=><g key={n}><line x1="45" x2="610" y1={y(n*max)} y2={y(n*max)} stroke="#e8edf2"/><text x="34" y={y(n*max)+4} textAnchor="end">{Math.round(n*max)}</text></g>)}<path d={path('active')+` L610,190 L45,190 Z`} fill="#fff0df"/><path d={path('active')} fill="none" stroke="#f58218" strokeWidth="2.5"/><path d={path('newcomers')} fill="none" stroke="#58a87a" strokeWidth="2"/>{data.map((d,i)=><g key={d.day}><circle cx={x(i)} cy={y(d.active)} r="3" fill="white" stroke="#f58218"><title>{date(d.day)} : {d.active} actifs, {d.newcomers} premières connexions</title></circle>{(i===0||i===data.length-1||i===Math.floor(data.length/2))&&<text x={x(i)} y="216" textAnchor={i===0?'start':i===data.length-1?'end':'middle'}>{new Date(d.day).toLocaleDateString('fr-FR',{month:'short',day:'numeric',timeZone:'UTC'})}</text>}</g>)}</svg>{data.every(d=>d.active===0)&&<p className="adm-chart-empty">Aucune connexion enregistrée sur cette période.</p>}</div>;
}
